/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const ReactAriaLazyImport = createFileRoute('/react-aria')()
const MaterialUiLazyImport = createFileRoute('/material-ui')()
const DownshiftLazyImport = createFileRoute('/downshift')()
const CmdkLazyImport = createFileRoute('/cmdk')()
const AriakitLazyImport = createFileRoute('/ariakit')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const ReactAriaLazyRoute = ReactAriaLazyImport.update({
  path: '/react-aria',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/react-aria.lazy').then((d) => d.Route))

const MaterialUiLazyRoute = MaterialUiLazyImport.update({
  path: '/material-ui',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/material-ui.lazy').then((d) => d.Route))

const DownshiftLazyRoute = DownshiftLazyImport.update({
  path: '/downshift',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/downshift.lazy').then((d) => d.Route))

const CmdkLazyRoute = CmdkLazyImport.update({
  path: '/cmdk',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/cmdk.lazy').then((d) => d.Route))

const AriakitLazyRoute = AriakitLazyImport.update({
  path: '/ariakit',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/ariakit.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/ariakit': {
      id: '/ariakit'
      path: '/ariakit'
      fullPath: '/ariakit'
      preLoaderRoute: typeof AriakitLazyImport
      parentRoute: typeof rootRoute
    }
    '/cmdk': {
      id: '/cmdk'
      path: '/cmdk'
      fullPath: '/cmdk'
      preLoaderRoute: typeof CmdkLazyImport
      parentRoute: typeof rootRoute
    }
    '/downshift': {
      id: '/downshift'
      path: '/downshift'
      fullPath: '/downshift'
      preLoaderRoute: typeof DownshiftLazyImport
      parentRoute: typeof rootRoute
    }
    '/material-ui': {
      id: '/material-ui'
      path: '/material-ui'
      fullPath: '/material-ui'
      preLoaderRoute: typeof MaterialUiLazyImport
      parentRoute: typeof rootRoute
    }
    '/react-aria': {
      id: '/react-aria'
      path: '/react-aria'
      fullPath: '/react-aria'
      preLoaderRoute: typeof ReactAriaLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  AriakitLazyRoute,
  CmdkLazyRoute,
  DownshiftLazyRoute,
  MaterialUiLazyRoute,
  ReactAriaLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/ariakit",
        "/cmdk",
        "/downshift",
        "/material-ui",
        "/react-aria"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/ariakit": {
      "filePath": "ariakit.lazy.tsx"
    },
    "/cmdk": {
      "filePath": "cmdk.lazy.tsx"
    },
    "/downshift": {
      "filePath": "downshift.lazy.tsx"
    },
    "/material-ui": {
      "filePath": "material-ui.lazy.tsx"
    },
    "/react-aria": {
      "filePath": "react-aria.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
